USE sakila; 
-- List the number of films per category.
SELECT 
	category.name, 
	count(film.film_id) as number_films 
FROM film 
JOIN film_category
	ON film.film_id = film_category.film_id
JOIN category
	ON film_category.category_id = category.category_id
GROUP BY category.name;

-- Retrieve the store ID, city, and country for each store.
SELECT 
	store.store_id,
    city.city,
    country.country 
FROM store
JOIN address 
ON store.address_id = address.address_id
JOIN city
ON address.city_id = city.city_id
JOIN country
ON city.country_id = country.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, sum(payment.amount) as total_revenue
FROM store
JOIN staff 
ON store.store_id = staff.store_id
JOIN payment
ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;

-- Determine the average running time of films for each category.
SELECT
	category.name as category_name,
	film_category.category_id,
	avg(film.length) as average_time
FROM film_category
JOIN film 
ON film_category.film_id = film.film_id
JOIN category
ON film_category.category_id = category.category_id
GROUP BY film_category.category_id;

-- BONUS 
-- Identify the film categories with the longest average running time.
SELECT
	category.name as category_name,
	film_category.category_id,
	avg(film.length) as average_time
FROM film_category
JOIN film 
ON film_category.film_id = film.film_id
JOIN category
ON film_category.category_id = category.category_id
GROUP BY film_category.category_id 
ORDER BY average_time DESC
LIMIT 5; -- top 5 categories

-- Display the top 10 most frequently rented movies in descending order.
SELECT film.title as film_name,
count(rental.rental_id) as rental_frequency
FROM film
JOIN inventory
ON film.film_id = inventory.film_id
JOIN rental
ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id
ORDER BY rental_frequency DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT film.title, store.store_id, inventory.inventory_id
FROM film 
JOIN inventory
ON film.film_id = inventory.film_id
JOIN store
ON inventory.store_id = store.store_id
WHERE film.title = 'Academy Dinosaur' and store.store_id = 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

SELECT DISTINCT
    film.title,
    CASE
        WHEN IFNULL(inventory.inventory_id, 0) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability_status
FROM film
LEFT JOIN inventory
    ON film.film_id = inventory.film_id
ORDER BY film.title;
